### ISSUE TITLE
Verify the file as a valid image to avoid malicious files being downloaded.

### ISSUE THREAD

**Issue by payini** [App-vNext/Notifier#1]
https://github.com/App-vNext/Notifier/blob/33617791728b892e227e3066254a585cb3a4ac1b/src/AppVNext.Notifier.ConsoleUwp/Notifier.cs#L216

**Comment by rxeno** [comment]
cool

**Comment by payini** [comment]
Done!

**Comment by rxeno** [comment]
Excellent . Always good to get to this point eh!?

**Comment by payini** [comment]
Indeed!
